### ISSUE TITLE
Patching .lib / .dll.a files

### ISSUE THREAD

**Issue by ghost** [njsmith/redll#3]
Does this support that?

**Comment by njsmith** [comment]
It doesn't, but probably something could be written that did; they're not terribly complicated. What exactly are you trying to do though?

**Comment by ghost** [comment]
I need to rename a DLL and I have the lib file. I already know how to do that but I currently don't have the time.

**Comment by njsmith** [comment]
Yeah, I'm not sure what the best solution for that is. (And unfortunately I don't have the time to solve it myself either right now.) There are a few possibilities:

* Use the old lib file when compiling new stuff, so that it's linked against the old DLL name, then use machomachomangler's redll feature to patch the binary to point to the new DLL name instead

* After renaming the DLL, regenerate the .lib file ([ref](https://wiki.videolan.org/GenerateLibFromDll/), [ref](https://adrianhenke.wordpress.com/2008/12/05/create-lib-file-from-dll/), etc.). The caveat here is that I think these references all assume that the DLL is only exporting functions, not variables -- a .lib file is basically just a set of tuples (symbol name, dll name, flag: is this symbol a variable or a function?). If one wants to avoid dumpbin then it should be possible to do something similar with objdump or machomachomangler.

* In theory it should be possible to read a .lib file and rewrite it, but this is complicated because .lib files actually have two formats: a simple one that MSVC generates, and a much more complicated one that mingw-w64 tools generate. Reading the MSVC style one is pretty simple. The mingw-w64... I dunno. Maybe one could kludge something that works "well enough" without too much work.

* If you have the .def file, this makes life *much* easier, you can just change the dll name at the top and regenerate the .lib from that

**Comment by ghost** [comment]
Closing as this is no longer needed.
